### ISSUE TITLE
On Windows 10 clicking the exit button does not close the app.

### ISSUE THREAD

**Issue by kaseyhinton** [socketsupply/union-app-studio#15] opened 2018-01-22 22:03 UTC
On Windows 10 trying to exit the app does not work. I had to manually kill the process to exit.

When I ran it locally if i commented out these 3 lines of code in /src/index.js  it functions as normal.
It looks like the global.quitting variable is undefined when is gets to onbeforeunload.

```javascript
window.onbeforeunload = function (e) {
  if (!remote.getGlobal('quitting')) return false
}
```

**Comment by asapzacy** [comment] 2018-01-22 23:39
trying to quit (by clicking X) both the app and the document window doesn't work on MacOS High Sierra 10.13.2

**Comment by heapwolf** [comment] 2018-01-23 10:03
@kaseyhinton this is a dupe of #7. I've never run it on Windows. But a PR would be welcome. It should be trivial.

@asapzacy this behavior is intended. Neither can exist without the other, closing one would break the other. Can you outline a more reasonable expectation for the behavior? I'm open to improving it.

**Closed as completed** 2018-01-23 10:06 UTC

**Comment by cassianomon** [comment] 2018-01-24 01:14
@0x00A what's the intention of the click on the X button? I thought it would close the program, but actually does nothing.

**Comment by asapzacy** [comment] 2018-01-25 00:16
@0x00A Could you minimize the Document Window and keep the editor open?

edit -- nevermind, saw 516f639 👍
